name: Build sqlbuilder

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        version:
          - 1.6.14
          - stable

    steps:
    - uses: actions/checkout@v1
    - uses: jiro4989/setup-nim-action@master
      with:
        nim-version: ${{ matrix.version }}

    - name: Print Nim version
      run: nim -v

    - name: Print Nimble version
      run: nimble -v

    - name: Build binaries
      run: nimble test